/* ===== DATA ===== */
const verbsDatabase = [
{v1:"backen",v2:"buk/backte",v3:"hat gebacken",translation:"печь",t1:"[ˈbakn̩]",t2:"[buːk]/[ˈbaktə]",t3:"[hat ɡəˈbakn̩]"},
{v1:"befehlen",v2:"befahl",v3:"hat befohlen",translation:"приказывать",t1:"[bəˈfeːlən]",t2:"[bəˈfaːl]",t3:"[hat bəˈfoːlən]"},
{v1:"beginnen",v2:"begann",v3:"hat begonnen",translation:"начинать",t1:"[bəˈɡɪnən]",t2:"[bəˈɡan]",t3:"[hat ɡəˈɡɔnən]"},
{v1:"beißen",v2:"biss",v3:"hat gebissen",translation:"кусать",t1:"[ˈbaɪ̯sn̩]",t2:"[bɪs]",t3:"[hat ɡəˈbɪsn̩]"},
{v1:"bergen",v2:"barg",v3:"hat geborgen",translation:"спасать",t1:"[ˈbɛʁɡn̩]",t2:"[baʁk]",t3:"[hat ɡəˈbɔʁɡn̩]"},
{v1:"bersten",v2:"barst",v3:"ist geborsten",translation:"лопнуть",t1:"[ˈbɛʁstn̩]",t2:"[baʁst]",t3:"[ɪst ɡəˈbɔʁstn̩]"},
{v1:"biegen",v2:"bog",v3:"hat gebogen",translation:"гнуть",t1:"[ˈbiːɡn̩]",t2:"[boːk]",t3:"[hat ɡəˈboːɡn̩]"},
{v1:"bieten",v2:"bot",v3:"hat geboten",translation:"предлагать",t1:"[ˈbiːtn̩]",t2:"[boːt]",t3:"[hat ɡəˈboːtn̩]"},
{v1:"binden",v2:"band",v3:"hat gebunden",translation:"связывать",t1:"[ˈbɪndn̩]",t2:"[bant]",t3:"[hat ɡəˈbʊndn̩]"},
{v1:"bitten",v2:"bat",v3:"hat gebeten",translation:"просить",t1:"[ˈbɪtn̩]",t2:"[baːt]",t3:"[hat ɡəˈbeːtn̩]"},
{v1:"blasen",v2:"blies",v3:"hat geblasen",translation:"дуть",t1:"[ˈblaːzn̩]",t2:"[bliːs]",t3:"[hat ɡəˈblaːzn̩]"},
{v1:"bleiben",v2:"blieb",v3:"ist geblieben",translation:"оставаться",t1:"[ˈblaɪ̯bn̩]",t2:"[bliːp]",t3:"[ɪst ɡəˈbliːbn̩]"},
{v1:"braten",v2:"briet",v3:"hat gebraten",translation:"жарить",t1:"[ˈbʁaːtn̩]",t2:"[bʁiːt]",t3:"[hat ɡəˈbʁaːtn̩]"},
{v1:"brechen",v2:"brach",v3:"hat/ist gebrochen",translation:"ломать",t1:"[ˈbʁɛçn̩]",t2:"[bʁaːx]",t3:"[hat/ɪst ɡəˈbʁɔxn̩]"},
{v1:"brennen",v2:"brannte",v3:"hat gebrannt",translation:"гореть",t1:"[ˈbʁɛnən]",t2:"[ˈbʁantə]",t3:"[hat ɡəˈbʁant]"},
{v1:"bringen",v2:"brachte",v3:"hat gebracht",translation:"приносить",t1:"[ˈbʁɪŋən]",t2:"[ˈbʁaxtə]",t3:"[hat ɡəˈbʁaxt]"},
{v1:"denken",v2:"dachte",v3:"hat gedacht",translation:"думать",t1:"[ˈdɛŋkn̩]",t2:"[ˈdaxtə]",t3:"[hat ɡəˈdaxt]"},
{v1:"dreschen",v2:"drosch",v3:"hat gedroschen",translation:"молотить",t1:"[ˈdʁɛʃn̩]",t2:"[dʁɔʃ]",t3:"[hat ɡəˈdʁɔʃn̩]"},
{v1:"dringen",v2:"drang",v3:"hat/ist gedrungen",translation:"проникать",t1:"[ˈdʁɪŋən]",t2:"[dʁaŋ]",t3:"[hat/ɪst ɡəˈdʁʊŋən]"},
{v1:"dürfen",v2:"durfte",v3:"hat gedurft",translation:"мочь (иметь разрешение)",t1:"[ˈdʏʁfn̩]",t2:"[ˈdʊʁftə]",t3:"[hat ɡəˈdʊʁft]"},
{v1:"empfangen",v2:"empfing",v3:"hat empfangen",translation:"принимать",t1:"[ɛmˈpfaŋən]",t2:"[ɛmˈpfiŋ]",t3:"[hat ɛmˈpfaŋən]"},
{v1:"empfehlen",v2:"empfahl",v3:"hat empfohlen",translation:"рекомендовать",t1:"[ɛmˈpfeːlən]",t2:"[ɛmˈpfaːl]",t3:"[hat ɛmˈpfoːlən]"},
{v1:"erlöschen",v2:"erlosch",v3:"ist erloschen",translation:"потухать, прекращаться",t1:"[ɛɐ̯ˈlœʃn̩]",t2:"[ɛɐ̯ˈlɔʃ]",t3:"[ɪst ɛɐ̯ˈlɔʃn̩]"},
{v1:"erschrecken",v2:"erschrak",v3:"ist erschrocken",translation:"пугаться",t1:"[ɛɐ̯ˈʃʁɛkn̩]",t2:"[ɛɐ̯ˈʃʁaːk]",t3:"[ɪst ɛɐ̯ˈʃʁɔkn̩]"},
{v1:"essen",v2:"aß",v3:"hat gegessen",translation:"есть, кушать",t1:"[ˈɛsn̩]",t2:"[aːs]",t3:"[hat ɡəˈɡɛsn̩]"},
{v1:"fahren",v2:"fuhr",v3:"hat/ist gefahren",translation:"ехать, везти",t1:"[ˈfaːʁən]",t2:"[fuːɐ̯]",t3:"[hat/ɪst ɡəˈfaːʁən]"},
{v1:"fallen",v2:"fiel",v3:"ist gefallen",translation:"падать",t1:"[ˈfalən]",t2:"[fiːl]",t3:"[ɪst ɡəˈfalən]"},
{v1:"fangen",v2:"fing",v3:"hat gefangen",translation:"ловить",t1:"[ˈfaŋən]",t2:"[fɪŋ]",t3:"[hat ɡəˈfaŋən]"},
{v1:"fechten",v2:"focht",v3:"hat gefochten",translation:"фехтовать",t1:"[ˈfɛçtn̩]",t2:"[fɔxt]",t3:"[hat ɡəˈfɔxtn̩]"},
{v1:"finden",v2:"fand",v3:"hat gefunden",translation:"находить",t1:"[ˈfɪndn̩]",t2:"[fant]",t3:"[hat ɡəˈfʊndn̩]"},
{v1:"flechten",v2:"flocht",v3:"hat geflochten",translation:"плести",t1:"[ˈflɛçtn̩]",t2:"[flɔxt]",t3:"[hat ɡəˈflɔxtn̩]"},
{v1:"fliegen",v2:"flog",v3:"hat/ist geflogen",translation:"летать",t1:"[ˈfliːɡn̩]",t2:"[floːk]",t3:"[hat/ɪst ɡəˈfloːɡn̩]"},
{v1:"fliehen",v2:"floh",v3:"ist geflohen",translation:"убегать, избегать",t1:"[ˈfliːən]",t2:"[floː]",t3:"[ɪst ɡəˈfloːən]"},
{v1:"fließen",v2:"floss",v3:"ist geflossen",translation:"течь, литься",t1:"[ˈfliːsn̩]",t2:"[flɔs]",t3:"[ɪst ɡəˈflɔsn̩]"},
{v1:"fressen",v2:"fraß",v3:"hat gefressen",translation:"жрать, грызть",t1:"[ˈfʁɛsn̩]",t2:"[fʁaːs]",t3:"[hat ɡəˈfʁɛsn̩]"},
{v1:"frieren",v2:"fror",v3:"hat gefroren",translation:"замерзать",t1:"[ˈfʁiːʁən]",t2:"[fʁoːɐ̯]",t3:"[hat ɡəˈfʁoːʁən]"},
{v1:"gären",v2:"gor",v3:"hat gegoren",translation:"бродить",t1:"[ˈɡɛːʁən]",t2:"[ɡoːɐ̯]",t3:"[hat ɡəˈɡoːʁən]"},
{v1:"gebären",v2:"gebar",v3:"hat/ist geboren",translation:"родить",t1:"[ɡəˈbɛːʁən]",t2:"[ɡəˈbaːɐ̯]",t3:"[hat/ɪst ɡəˈboːʁən]"},
{v1:"geben",v2:"gab",v3:"hat gegeben",translation:"давать",t1:"[ˈɡeːbn̩]",t2:"[ɡaːp]",t3:"[hat ɡəˈɡeːbn̩]"},
{v1:"gedeihen",v2:"gedieh",v3:"ist gediehen",translation:"расти, преуспевать",t1:"[ɡəˈdaɪ̯ən]",t2:"[ɡəˈdiː]",t3:"[ɪst ɡəˈdiːən]"},
{v1:"gehen",v2:"ging",v3:"ist gegangen",translation:"идти, ходить",t1:"[ˈɡeːən]",t2:"[ɡɪŋ]",t3:"[ɪst ɡəˈɡaŋən]"},
{v1:"gelingen",v2:"gelang",v3:"ist gelungen",translation:"удаваться",t1:"[ɡəˈlɪŋən]",t2:"[ɡəˈlaŋ]",t3:"[ɪst ɡəˈlʊŋən]"},
{v1:"gelten",v2:"galt",v3:"hat gegolten",translation:"стоить, цениться",t1:"[ˈɡɛltn̩]",t2:"[ɡalt]",t3:"[hat ɡəˈɡɔltn̩]"},
{v1:"genesen",v2:"genas",v3:"ist genesen",translation:"выздоравливать",t1:"[ɡəˈneːzn̩]",t2:"[ɡəˈnaːs]",t3:"[ɪst ɡəˈneːzn̩]"},
{v1:"genießen",v2:"genoss",v3:"hat genossen",translation:"наслаждаться",t1:"[ɡəˈniːsn̩]",t2:"[ɡəˈnɔs]",t3:"[hat ɡəˈnɔsn̩]"},
{v1:"geschehen",v2:"geschah",v3:"ist geschehen",translation:"происходить",t1:"[ɡəˈʃeːən]",t2:"[ɡəˈʃaː]",t3:"[ɪst ɡəˈʃeːən]"},
{v1:"gewinnen",v2:"gewann",v3:"hat gewonnen",translation:"выигрывать",t1:"[ɡəˈvɪnən]",t2:"[ɡəˈvan]",t3:"[hat ɡəˈvɔnən]"},
{v1:"gießen",v2:"goss",v3:"hat gegossen",translation:"лить, наливать",t1:"[ˈɡiːsn̩]",t2:"[ɡɔs]",t3:"[hat ɡəˈɡɔsn̩]"},
{v1:"gleichen",v2:"glich",v3:"hat geglichen",translation:"быть похожим, выравнивать",t1:"[ˈɡlaɪ̯çn̩]",t2:"[ɡlɪç]",t3:"[hat ɡəˈɡlɪçn̩]"},
{v1:"gleiten",v2:"glitt",v3:"ist geglitten",translation:"скользить",t1:"[ˈɡlaɪ̯tn̩]",t2:"[ɡlɪt]",t3:"[ɪst ɡəˈɡlɪtn̩]"},
{v1:"graben",v2:"grub",v3:"hat gegraben",translation:"копать",t1:"[ˈɡʁaːbn̩]",t2:"[ɡʁuːp]",t3:"[hat ɡəˈɡʁaːbn̩]"},
{v1:"greifen",v2:"griff",v3:"hat gegriffen",translation:"браться (за что-л.)",t1:"[ˈɡʁaɪ̯fn̩]",t2:"[ɡʁɪf]",t3:"[hat ɡəˈɡʁɪfn̩]"},
{v1:"haben",v2:"hatte",v3:"hat gehabt",translation:"иметь",t1:"[ˈhaːbn̩]",t2:"[ˈhatə]",t3:"[hat ɡəˈhapt]"},
{v1:"halten",v2:"hielt",v3:"hat gehalten",translation:"держать",t1:"[ˈhaltn̩]",t2:"[hiːlt]",t3:"[hat ɡəˈhaltn̩]"},
{v1:"hängen",v2:"hing",v3:"hat gehangen",translation:"висеть",t1:"[ˈhɛŋən]",t2:"[hɪŋ]",t3:"[hat ɡəˈhaŋən]"},
{v1:"hauen",v2:"hieb/haute",v3:"hat/ist gehauen",translation:"рубить",t1:"[ˈhaʊ̯ən]",t2:"[hiːp]/[ˈhaʊ̯tə]",t3:"[hat/ɪst ɡəˈhaʊ̯ən]"},
{v1:"heben",v2:"hob",v3:"hat gehoben",translation:"поднимать",t1:"[ˈheːbn̩]",t2:"[hoːp]",t3:"[hat ɡəˈhoːbn̩]"},
{v1:"heißen",v2:"hieß",v3:"hat geheißen",translation:"называться",t1:"[ˈhaɪ̯sn̩]",t2:"[hiːs]",t3:"[hat ɡəˈhaɪ̯sn̩]"},
{v1:"helfen",v2:"half",v3:"hat geholfen",translation:"помогать",t1:"[ˈhɛlfn̩]",t2:"[half]",t3:"[hat ɡəˈhɔlfn̩]"},
{v1:"kennen",v2:"kannte",v3:"hat gekannt",translation:"знать",t1:"[ˈkɛnən]",t2:"[ˈkantə]",t3:"[hat ɡəˈkant]"},
{v1:"klingen",v2:"klang",v3:"hat geklungen",translation:"звенеть",t1:"[ˈklɪŋən]",t2:"[klaŋ]",t3:"[hat ɡəˈklʊŋən]"},
{v1:"kneifen",v2:"kniff",v3:"hat gekniffen",translation:"щипать",t1:"[ˈknaɪ̯fn̩]",t2:"[knɪf]",t3:"[hat ɡəˈknɪfn̩]"},
{v1:"kommen",v2:"kam",v3:"ist gekommen",translation:"приходить",t1:"[ˈkɔmən]",t2:"[kaːm]",t3:"[ɪst ɡəˈkɔmən]"},
{v1:"können",v2:"konnte",v3:"hat gekonnt",translation:"мочь",t1:"[ˈkœnən]",t2:"[ˈkɔntə]",t3:"[hat ɡəˈkɔnt]"},
{v1:"kriechen",v2:"kroch",v3:"ist gekrochen",translation:"ползти",t1:"[ˈkʁiːçn̩]",t2:"[kʁɔx]",t3:"[ɪst ɡəˈkʁɔxn̩]"},
{v1:"laden",v2:"lud",v3:"hat geladen",translation:"грузить, приглашать",t1:"[ˈlaːdn̩]",t2:"[luːt]",t3:"[hat ɡəˈlaːdn̩]"},
{v1:"lassen",v2:"ließ",v3:"hat gelassen",translation:"позволять, велеть, оставлять",t1:"[ˈlasn̩]",t2:"[liːs]",t3:"[hat ɡəˈlasn̩]"},
{v1:"laufen",v2:"lief",v3:"ist gelaufen",translation:"бегать",t1:"[ˈlaʊ̯fn̩]",t2:"[liːf]",t3:"[ɪst ɡəˈlaʊ̯fn̩]"},
{v1:"leiden",v2:"litt",v3:"hat gelitten",translation:"страдать, терпеть",t1:"[ˈlaɪ̯dn̩]",t2:"[lɪt]",t3:"[hat ɡəˈlɪtn̩]"},
{v1:"leihen",v2:"lieh",v3:"hat geliehen",translation:"одалживать",t1:"[ˈlaɪ̯ən]",t2:"[liː]",t3:"[hat ɡəˈliːən]"},
{v1:"lesen",v2:"las",v3:"hat gelesen",translation:"читать",t1:"[ˈleːzn̩]",t2:"[laːs]",t3:"[hat ɡəˈleːzn̩]"},
{v1:"liegen",v2:"lag",v3:"hat gelegen",translation:"лежать",t1:"[ˈliːɡn̩]",t2:"[laːk]",t3:"[hat ɡəˈleːɡn̩]"},
{v1:"löschen",v2:"losch",v3:"hat geloschen",translation:"тушить, стирать",t1:"[ˈlœʃn̩]",t2:"[lɔʃ]",t3:"[hat ɡəˈlɔʃn̩]"},
{v1:"lügen",v2:"log",v3:"hat gelogen",translation:"лгать",t1:"[ˈlyːɡn̩]",t2:"[loːk]",t3:"[hat ɡəˈloːɡn̩]"},
{v1:"mahlen",v2:"mahlte",v3:"hat gemahlen",translation:"молоть",t1:"[ˈmaːlən]",t2:"[ˈmaːltə]",t3:"[hat ɡəˈmaːln̩]"},
{v1:"meiden",v2:"mied",v3:"hat gemieden",translation:"избегать",t1:"[ˈmaɪ̯dn̩]",t2:"[miːt]",t3:"[hat ɡəˈmiːdn̩]"},
{v1:"melken",v2:"melkte",v3:"hat gemolken/gemelkt",translation:"доить",t1:"[ˈmɛlkn̩]",t2:"[ˈmɛlktə]",t3:"[hat ɡəˈmɔlkn̩]"},
{v1:"messen",v2:"maß",v3:"hat gemessen",translation:"измерять",t1:"[ˈmɛsn̩]",t2:"[maːs]",t3:"[hat ɡəˈmɛsn̩]"},
{v1:"misslingen",v2:"misslang",v3:"ist misslungen",translation:"не удаваться",t1:"[mɪsˈlɪŋən]",t2:"[mɪsˈlaŋ]",t3:"[ɪst mɪsˈlʊŋən]"},
{v1:"mögen",v2:"mochte",v3:"hat gemocht",translation:"любить, хотеть",t1:"[ˈmøːɡn̩]",t2:"[ˈmɔxtə]",t3:"[hat ɡəˈmɔxt]"},
{v1:"müssen",v2:"musste",v3:"hat gemusst",translation:"должным быть",t1:"[ˈmʏsn̩]",t2:"[ˈmʊstə]",t3:"[hat ɡəˈmʊst]"},
{v1:"nehmen",v2:"nahm",v3:"hat genommen",translation:"брать",t1:"[ˈneːmən]",t2:"[naːm]",t3:"[hat ɡəˈnɔmən]"},
{v1:"nennen",v2:"nannte",v3:"hat genannt",translation:"называть",t1:"[ˈnɛnən]",t2:"[ˈnantə]",t3:"[hat ɡəˈnant]"},
{v1:"pfeifen",v2:"pfiff",v3:"hat gepfiffen",translation:"свистеть",t1:"[ˈpfaɪ̯fn̩]",t2:"[pfɪf]",t3:"[hat ɡəˈpfɪfn̩]"},
{v1:"preisen",v2:"pries",v3:"hat gepriesen",translation:"хвалить",t1:"[ˈpʁaɪ̯zn̩]",t2:"[pʁiːs]",t3:"[hat ɡəˈpʁiːzn̩]"},
{v1:"quellen",v2:"quoll",v3:"ist gequollen",translation:"быть, бить ключом",t1:"[ˈkvɛlən]",t2:"[kvɔl]",t3:"[ɪst ɡəˈkvɔlən]"},
{v1:"raten",v2:"riet",v3:"hat geraten",translation:"советовать",t1:"[ˈʁaːtn̩]",t2:"[ʁiːt]",t3:"[hat ɡəˈʁaːtn̩]"},
{v1:"reiben",v2:"rieb",v3:"hat gerieben",translation:"тереть",t1:"[ˈʁaɪ̯bn̩]",t2:"[ʁiːp]",t3:"[hat ɡəˈʁiːbn̩]"},
{v1:"reißen",v2:"riss",v3:"hat/ist gerissen",translation:"рвать",t1:"[ˈʁaɪ̯sn̩]",t2:"[ʁɪs]",t3:"[hat/ɪst ɡəˈʁɪsn̩]"},
{v1:"reiten",v2:"ritt",v3:"hat/ist geritten",translation:"ездить верхом",t1:"[ˈʁaɪ̯tn̩]",t2:"[ʁɪt]",t3:"[hat/ɪst ɡəˈʁɪtn̩]"},
{v1:"rennen",v2:"rannte",v3:"ist gerannt",translation:"бежать",t1:"[ˈʁɛnən]",t2:"[ˈʁantə]",t3:"[ɪst ɡəˈʁant]"},
{v1:"riechen",v2:"roch",v3:"hat gerochen",translation:"нюхать",t1:"[ˈʁiːçn̩]",t2:"[ʁɔx]",t3:"[hat ɡəˈʁɔxn̩]"},
{v1:"ringen",v2:"rang",v3:"hat gerungen",translation:"бороться, добиваться",t1:"[ˈʁɪŋən]",t2:"[ʁaŋ]",t3:"[hat ɡəˈʁʊŋən]"},
{v1:"rinnen",v2:"rann",v3:"ist geronnen",translation:"течь",t1:"[ˈʁɪnən]",t2:"[ʁan]",t3:"[ɪst ɡəˈʁɔnən]"},
{v1:"rufen",v2:"rief",v3:"hat gerufen",translation:"кричать, звать",t1:"[ˈʁuːfn̩]",t2:"[ʁiːf]",t3:"[hat ɡəˈʁuːfn̩]"},
{v1:"salzen",v2:"salzte",v3:"hat gesalzen/gesalzt",translation:"солить",t1:"[ˈzaltsn̩]",t2:"[ˈzaltsə]",t3:"[hat ɡəˈzaltsn̩]"},
{v1:"saufen",v2:"soff",v3:"hat gesoffen",translation:"пить, пьянствовать",t1:"[ˈzaʊ̯fn̩]",t2:"[zɔf]",t3:"[hat ɡəˈzɔfn̩]"},
{v1:"saugen",v2:"sog/saugte",v3:"hat gesogen/gesaugt",translation:"сосать",t1:"[ˈzaʊ̯ɡn̩]",t2:"[zoːk]/[ˈzaʊ̯ɡtə]",t3:"[hat ɡəˈzoːɡn̩]"},
{v1:"schaffen",v2:"schuf",v3:"hat geschaffen",translation:"создавать, творить",t1:"[ˈʃafn̩]",t2:"[ʃuːf]",t3:"[hat ɡəˈʃafn̩]"},
{v1:"scheiden",v2:"schied",v3:"hat/ist geschieden",translation:"разделять",t1:"[ˈʃaɪ̯dn̩]",t2:"[ʃiːt]",t3:"[hat/ɪst ɡəˈʃiːdn̩]"},
{v1:"scheinen",v2:"schien",v3:"hat geschienen",translation:"светить, сиять",t1:"[ˈʃaɪ̯nən]",t2:"[ʃiːn]",t3:"[hat ɡəˈʃiːnən]"},
{v1:"schelten",v2:"schalt",v3:"hat gescholten",translation:"бранить",t1:"[ˈʃɛltn̩]",t2:"[ʃalt]",t3:"[hat ɡəˈʃɔltn̩]"},
{v1:"scheren",v2:"schor",v3:"hat geschoren",translation:"стричь",t1:"[ˈʃeːʁən]",t2:"[ʃoːɐ̯]",t3:"[hat ɡəˈʃoːʁən]"},
{v1:"schieben",v2:"schob",v3:"hat geschoben",translation:"двигать, толкать",t1:"[ˈʃiːbn̩]",t2:"[ʃoːp]",t3:"[hat ɡəˈʃoːbn̩]"},
{v1:"schießen",v2:"schoss",v3:"hat/ist geschossen",translation:"стрелять",t1:"[ˈʃiːsn̩]",t2:"[ʃɔs]",t3:"[hat/ɪst ɡəˈʃɔsn̩]"},
{v1:"schlafen",v2:"schlief",v3:"hat geschlafen",translation:"спать",t1:"[ˈʃlaːfn̩]",t2:"[ʃliːf]",t3:"[hat ɡəˈʃlaːfn̩]"},
{v1:"schlagen",v2:"schlug",v3:"hat geschlagen",translation:"бить",t1:"[ˈʃlaːɡn̩]",t2:"[ʃluːk]",t3:"[hat ɡəˈʃlaːɡn̩]"},
{v1:"schleichen",v2:"schlich",v3:"ist geschlichen",translation:"красться",t1:"[ˈʃlaɪ̯çn̩]",t2:"[ʃlɪç]",t3:"[ɪst ɡəˈʃlɪçn̩]"},
{v1:"schleifen",v2:"schliff",v3:"hat geschliffen",translation:"точить",t1:"[ˈʃlaɪ̯fn̩]",t2:"[ʃlɪf]",t3:"[hat ɡəˈʃlɪfn̩]"},
{v1:"schließen",v2:"schloss",v3:"hat geschlossen",translation:"закрывать",t1:"[ˈʃliːsn̩]",t2:"[ʃlɔs]",t3:"[hat ɡəˈʃlɔsn̩]"},
{v1:"schlingen",v2:"schlang",v3:"hat geschlungen",translation:"обвивать",t1:"[ˈʃlɪŋən]",t2:"[ʃlaŋ]",t3:"[hat ɡəˈʃlʊŋən]"},
{v1:"schmeißen",v2:"schmiss",v3:"hat geschmissen",translation:"кидать, бросать",t1:"[ˈʃmaɪ̯sn̩]",t2:"[ʃmɪs]",t3:"[hat ɡəˈʃmɪsn̩]"},
{v1:"schmelzen",v2:"schmolz",v3:"hat/ist geschmolzen",translation:"таять",t1:"[ˈʃmɛltsn̩]",t2:"[ʃmɔlts]",t3:"[hat/ɪst ɡəˈʃmɔltsn̩]"},
{v1:"schneiden",v2:"schnitt",v3:"hat geschnitten",translation:"резать",t1:"[ˈʃnaɪ̯dn̩]",t2:"[ʃnɪt]",t3:"[hat ɡəˈʃnɪtn̩]"},
{v1:"schreiben",v2:"schrieb",v3:"hat geschrieben",translation:"писать",t1:"[ˈʃʁaɪ̯bn̩]",t2:"[ʃʁiːp]",t3:"[hat ɡəˈʃʁiːbn̩]"},
{v1:"schreien",v2:"schrie",v3:"hat geschrien",translation:"кричать",t1:"[ˈʃʁaɪ̯ən]",t2:"[ʃʁiː]",t3:"[hat ɡəˈʃʁiːn]"},
{v1:"schreiten",v2:"schritt",v3:"ist geschritten",translation:"шагать",t1:"[ˈʃʁaɪ̯tn̩]",t2:"[ʃʁɪt]",t3:"[ɪst ɡəˈʃʁɪtn̩]"},
{v1:"schweigen",v2:"schwieg",v3:"hat geschwiegen",translation:"молчать",t1:"[ˈʃvaɪ̯ɡn̩]",t2:"[ʃviːk]",t3:"[hat ɡəˈʃviːɡn̩]"},
{v1:"schwellen",v2:"schwoll",v3:"ist geschwollen",translation:"пухнуть",t1:"[ˈʃvɛlən]",t2:"[ʃvɔl]",t3:"[ɪst ɡəˈʃvɔlən]"},
{v1:"schwimmen",v2:"schwamm",v3:"hat/ist geschwommen",translation:"плавать",t1:"[ˈʃvɪmən]",t2:"[ʃvam]",t3:"[hat/ɪst ɡəˈʃvɔmən]"},
{v1:"schwinden",v2:"schwand",v3:"ist geschwunden",translation:"убывать, исчезать",t1:"[ˈʃvɪndn̩]",t2:"[ʃvant]",t3:"[ɪst ɡəˈʃvʊndn̩]"},
{v1:"schwingen",v2:"schwang",v3:"hat geschwungen",translation:"махать, размахивать",t1:"[ˈʃvɪŋən]",t2:"[ʃvaŋ]",t3:"[hat ɡəˈʃvʊŋən]"},
{v1:"schwören",v2:"schwor/schwur",v3:"hat geschworen",translation:"клясться",t1:"[ˈʃvøːʁən]",t2:"[ʃvoːɐ̯]/[ʃvuːɐ̯]",t3:"[hat ɡəˈʃvoːʁən]"},
{v1:"sehen",v2:"sah",v3:"hat gesehen",translation:"смотреть",t1:"[ˈzeːən]",t2:"[zaː]",t3:"[hat ɡəˈzeːən]"},
{v1:"sein",v2:"war",v3:"ist gewesen",translation:"быть",t1:"[zaɪ̯n]",t2:"[vaːɐ̯]",t3:"[ɪst ɡəˈveːzn̩]"},
{v1:"senden",v2:"sandte",v3:"hat gesandt",translation:"посылать, отсылать",t1:"[ˈzɛndn̩]",t2:"[ˈzantə]",t3:"[hat ɡəˈzant]"},
{v1:"singen",v2:"sang",v3:"hat gesungen",translation:"петь",t1:"[ˈzɪŋən]",t2:"[zaŋ]",t3:"[hat ɡəˈzʊŋən]"},
{v1:"sinken",v2:"sank",v3:"ist gesunken",translation:"снижаться, погружаться, тонуть",t1:"[ˈzɪŋkn̩]",t2:"[zaŋk]",t3:"[ɪst ɡəˈzʊŋkn̩]"},
{v1:"sinnen",v2:"sann",v3:"hat gesonnen",translation:"думать, размышлять",t1:"[ˈzɪnən]",t2:"[zan]",t3:"[hat ɡəˈzɔnən]"},
{v1:"sitzen",v2:"saß",v3:"hat gesessen",translation:"сидеть",t1:"[ˈzɪtsn̩]",t2:"[zaːs]",t3:"[hat ɡəˈzɛsn̩]"},
{v1:"sollen",v2:"sollte",v3:"hat gesollt",translation:"быть должным",t1:"[ˈzɔlən]",t2:"[ˈzɔltə]",t3:"[hat ɡəˈzɔlt]"},
{v1:"spielen",v2:"spielte",v3:"hat gespielt",translation:"играть",t1:"[ˈʃpiːlən]",t2:"[ˈʃpiːltə]",t3:"[hat ɡəˈʃpiːlt]"},
{v1:"spinnen",v2:"spann",v3:"hat gesponnen",translation:"прясть",t1:"[ˈʃpɪnən]",t2:"[ʃpan]",t3:"[hat ɡəˈʃpɔnən]"},
{v1:"sprechen",v2:"sprach",v3:"hat gesprochen",translation:"говорить",t1:"[ˈʃpʁɛçn̩]",t2:"[ʃpʁaːx]",t3:"[hat ɡəˈʃpʁɔxn̩]"},
{v1:"sprießen",v2:"spross",v3:"ist gesprossen",translation:"пускать ростки, почки",t1:"[ˈʃpʁiːsn̩]",t2:"[ʃpʁɔs]",t3:"[ɪst ɡəˈʃpʁɔsn̩]"},
{v1:"springen",v2:"sprang",v3:"ist gesprungen",translation:"прыгать, скакать",t1:"[ˈʃpʁɪŋən]",t2:"[ʃpʁaŋ]",t3:"[ɪst ɡəˈʃpʁʊŋən]"},
{v1:"stechen",v2:"stach",v3:"hat gestochen",translation:"колоть",t1:"[ˈʃtɛçn̩]",t2:"[ʃtaːx]",t3:"[hat ɡəˈʃtɔxn̩]"},
{v1:"stehen",v2:"stand",v3:"hat gestanden",translation:"стоять, находиться",t1:"[ˈʃteːən]",t2:"[ʃtant]",t3:"[hat ɡəˈʃtandn̩]"},
{v1:"stehlen",v2:"stahl",v3:"hat gestohlen",translation:"воровать",t1:"[ˈʃteːlən]",t2:"[ʃtaːl]",t3:"[hat ɡəˈʃtoːlən]"},
{v1:"steigen",v2:"stieg",v3:"ist gestiegen",translation:"подниматься",t1:"[ˈʃtaɪ̯ɡn̩]",t2:"[ʃtiːk]",t3:"[ɪst ɡəˈʃtiːɡn̩]"},
{v1:"sterben",v2:"starb",v3:"ist gestorben",translation:"умирать",t1:"[ˈʃtɛʁbn̩]",t2:"[ʃtaʁp]",t3:"[ɪst ɡəˈʃtɔʁbn̩]"},
{v1:"stieben",v2:"stob",v3:"hat/ist gestoben",translation:"рассеиваться",t1:"[ˈʃtiːbn̩]",t2:"[ʃtoːp]",t3:"[hat/ɪst ɡəˈʃtoːbn̩]"},
{v1:"stoßen",v2:"stieß",v3:"hat/ist gestoßen",translation:"толкать",t1:"[ˈʃtoːsn̩]",t2:"[ʃtiːs]",t3:"[hat/ɪst ɡəˈʃtoːsn̩]"},
{v1:"streichen",v2:"strich",v3:"hat gestrichen",translation:"гладить",t1:"[ˈʃtʁaɪ̯çn̩]",t2:"[ʃtʁɪç]",t3:"[hat ɡəˈʃtʁɪçn̩]"},
{v1:"streiten",v2:"stritt",v3:"hat gestritten",translation:"спорить",t1:"[ˈʃtʁaɪ̯tn̩]",t2:"[ʃtʁɪt]",t3:"[hat ɡəˈʃtʁɪtn̩]"},
{v1:"tragen",v2:"trug",v3:"hat getragen",translation:"носить",t1:"[ˈtʁaːɡn̩]",t2:"[tʁuːk]",t3:"[hat ɡəˈtʁaːɡn̩]"},
{v1:"treffen",v2:"traf",v3:"hat getroffen",translation:"встречать",t1:"[ˈtʁɛfn̩]",t2:"[tʁaːf]",t3:"[hat ɡəˈtʁɔfn̩]"},
{v1:"treiben",v2:"trieb",v3:"hat/ist getrieben",translation:"гнать",t1:"[ˈtʁaɪ̯bn̩]",t2:"[tʁiːp]",t3:"[hat/ɪst ɡəˈtʁiːbn̩]"},
{v1:"treten",v2:"trat",v3:"hat/ist getreten",translation:"ступать",t1:"[ˈtʁeːtn̩]",t2:"[tʁaːt]",t3:"[hat/ɪst ɡəˈtʁeːtn̩]"},
{v1:"trinken",v2:"trank",v3:"hat getrunken",translation:"пить",t1:"[ˈtʁɪŋkn̩]",t2:"[tʁaŋk]",t3:"[hat ɡəˈtʁʊŋkn̩]"},
{v1:"trügen",v2:"trog",v3:"hat getrogen",translation:"обманывать",t1:"[ˈtʁyːɡn̩]",t2:"[tʁoːk]",t3:"[hat ɡəˈtʁoːɡn̩]"},
{v1:"tun",v2:"tat",v3:"hat getan",translation:"делать",t1:"[tuːn]",t2:"[taːt]",t3:"[hat ɡəˈtaːn]"},
{v1:"verderben",v2:"verdarb",v3:"hat/ist verdorben",translation:"портить",t1:"[fɛɐ̯ˈdɛʁbn̩]",t2:"[fɛɐ̯ˈdaʁp]",t3:"[hat/ɪst fɛɐ̯ˈdɔʁbn̩]"},
{v1:"verdrießen",v2:"verdross",v3:"hat verdrossen",translation:"сердить, досаждать",t1:"[fɛɐ̯ˈdʁiːsn̩]",t2:"[fɛɐ̯ˈdʁɔs]",t3:"[hat fɛɐ̯ˈdʁɔsn̩]"},
{v1:"vergessen",v2:"vergaß",v3:"hat vergessen",translation:"забывать",t1:"[fɛɐ̯ˈɡɛsn̩]",t2:"[fɛɐ̯ˈɡaːs]",t3:"[hat fɛɐ̯ˈɡɛsn̩]"},
{v1:"verlieren",v2:"verlor",v3:"hat verloren",translation:"терять",t1:"[fɛɐ̯ˈliːʁən]",t2:"[fɛɐ̯ˈloːɐ̯]",t3:"[hat fɛɐ̯ˈloːʁən]"},
{v1:"verzeihen",v2:"verzieh",v3:"hat verziehen",translation:"прощать",t1:"[fɛɐ̯ˈtsaɪ̯ən]",t2:"[fɛɐ̯ˈtsiː]",t3:"[hat fɛɐ̯ˈtsiːən]"},
{v1:"weisen",v2:"wies",v3:"hat gewiesen",translation:"указывать",t1:"[ˈvaɪ̯zn̩]",t2:"[viːs]",t3:"[hat ɡəˈviːzn̩]"},
{v1:"wachsen",v2:"wuchs",v3:"ist gewachsen",translation:"расти",t1:"[ˈvaksn̩]",t2:"[vuːks]",t3:"[ɪst ɡəˈvaksn̩]"},
{v1:"wägen",v2:"wog",v3:"hat gewogen",translation:"взвешивать",t1:"[ˈvɛːɡn̩]",t2:"[voːk]",t3:"[hat ɡəˈvoːɡn̩]"},
{v1:"waschen",v2:"wusch",v3:"hat gewaschen",translation:"мыть",t1:"[ˈvaʃn̩]",t2:"[vuːʃ]",t3:"[hat ɡəˈvaʃn̩]"},
{v1:"weichen",v2:"wich",v3:"ist gewichen",translation:"уклоняться, уворачиваться",t1:"[ˈvaɪ̯çn̩]",t2:"[vɪç]",t3:"[ɪst ɡəˈvɪçn̩]"},
{v1:"wenden",v2:"wandte/wendete",v3:"hat gewandt/gewendet",translation:"поворачивать",t1:"[ˈvɛndn̩]",t2:"[ˈvantə]/[ˈvɛndetə]",t3:"[hat ɡəˈvant]/[ɡəˈvɛndet]"},
{v1:"werben",v2:"warb",v3:"hat geworben",translation:"рекламировать",t1:"[ˈvɛʁbn̩]",t2:"[vaʁp]",t3:"[hat ɡəˈvɔʁbn̩]"},
{v1:"werden",v2:"wurde",v3:"ist geworden",translation:"становиться",t1:"[ˈveːɐ̯dn̩]",t2:"[ˈvʊʁdə]",t3:"[ɪst ɡəˈvɔʁdn̩]"},
{v1:"werfen",v2:"warf",v3:"hat geworfen",translation:"кидать",t1:"[ˈvɛʁfn̩]",t2:"[vaʁf]",t3:"[hat ɡəˈvɔʁfn̩]"},
{v1:"wiegen",v2:"wog",v3:"hat gewogen",translation:"весить, вешать",t1:"[ˈviːɡn̩]",t2:"[voːk]",t3:"[hat ɡəˈvoːɡn̩]"},
{v1:"winden",v2:"wand",v3:"hat gewunden",translation:"вить",t1:"[ˈvɪndn̩]",t2:"[vant]",t3:"[hat ɡəˈvʊndn̩]"},
{v1:"wissen",v2:"wusste",v3:"hat gewusst",translation:"знать",t1:"[ˈvɪsn̩]",t2:"[ˈvʊstə]",t3:"[hat ɡəˈvʊst]"},
{v1:"wollen",v2:"wollte",v3:"hat gewollt",translation:"хотеть",t1:"[ˈvɔlən]",t2:"[ˈvɔltə]",t3:"[hat ɡəˈvɔlt]"},
{v1:"ziehen",v2:"zog",v3:"hat/ist gezogen",translation:"тянуть",t1:"[ˈtsiːən]",t2:"[tsoːk]",t3:"[hat/ɪst ɡəˈtsoːɡn̩]"},
{v1:"zwingen",v2:"zwang",v3:"hat gezwungen",translation:"принуждать",t1:"[ˈtsvɪŋən]",t2:"[tsvaŋ]",t3:"[hat ɡəˈtsvʊŋən]"}
];
